openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /user/{userId}:
    get:
      summary: Get user by ID
      description: Retrieve information about a user by their ID.
      parameters:
        - name: userId
          in: path
          description: ID of the user to retrieve
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                userId: 1
                username: john_doe
                email: john@example.com
        '404':
          description: User not found
          content:
            application/json:
              example:
                error: User not found